import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {build} from 'rolldown';
import ExcelJS from 'exceljs';
await fs.mkdir('work',{recursive:true});
await build({input:['app/excel-reader.ts','app/excel-import.tsx'],platform:'node',transform:{jsx:{runtime:'automatic'}},output:{dir:'work/excel-test',format:'esm'}});
const {readExcelSheets}=await import('../work/excel-test/excel-reader.js');
const {suggestMapping,mappedCSV}=await import('../work/excel-test/excel-import.js');
const w=new ExcelJS.Workbook();const s=w.addWorksheet('Base');
s.addRow(['Código','Descripción','Cantidad','Vencimiento']);
s.addRow([12,'Montura; azul',7,new Date('2027-03-09T00:00:00Z')]);
s.getCell('A2').numFmt='00000';s.getCell('D2').numFmt='yyyy-mm-dd';
const buffer=await w.xlsx.writeBuffer();
const sheets=await readExcelSheets({arrayBuffer:async()=>buffer.buffer.slice(buffer.byteOffset,buffer.byteOffset+buffer.byteLength)});
assert.equal(sheets[0].rows[1][0],'00012');assert.equal(sheets[0].rows[1][3],'2027-03-09');
const mapping=suggestMapping(sheets[0].rows[0]);assert.equal(mapping.nombre,1);assert.equal(mapping.existencias,2);
const csv=mappedCSV(sheets[0],1,mapping,'Montura');assert.match(csv,/"00012";"Montura; azul";"Montura";"7";"0";"0"/);
assert.match(csv,/"2027-03-09"/);assert.match(csv,/"Unidad"/);
s.getCell('C2').value={formula:'1+6'};
const formulaBuffer=await w.xlsx.writeBuffer();
await assert.rejects(readExcelSheets({arrayBuffer:async()=>formulaBuffer.buffer.slice(formulaBuffer.byteOffset,formulaBuffer.byteOffset+formulaBuffer.byteLength)}),/recalcula/);
console.log('PASS: Excel workbook reading, dates, leading zeros, header mapping, quoted values, defaults and missing formula result rejection.');
