import assert from 'node:assert/strict';import {localDatabase} from '../scripts/local-database.mjs';import {pilotAction} from '../dist/pilot/pilot.js';import {userMessage} from '../scripts/pilot-errors.mjs';
const {sqlite:db}=localDatabase(':memory:');db.prepare('INSERT INTO pilot_accounts VALUES(?,?,?,?,?)').run('h','Julieth Casanova','Habitual','fixture','fixture');db.prepare('INSERT INTO pilot_shifts(id,day,holiday,observations,status,delivered_by,delivered_at) VALUES(?,?,?,?,?,?,?)').run('s','2026-09-18',1,'Prueba','Entregado','h','fixture');
db.prepare('INSERT INTO products(id,code,name,category,minimum,maximum,stock,last_event,created_at) VALUES(?,?,?,?,0,0,1,?,?)').run('p','p','p','Montura','base','base');db.prepare('INSERT INTO pilot_lines(id,shift_id,product_id,code,name,initial,balance,observations) VALUES(?,?,?,?,?,1,1,?)').run('l','s','p','p','p','');
const input={action:'deliver',day:'2026-09-18',holiday:true,observations:'Prueba',lines:[{productId:'p',quantity:1}]};const h={id:'h',name:'Julieth Casanova',role:'Habitual'};
assert.throws(()=>pilotAction(db,h,input),e=>e.message.includes('18/09/2026')&&e.message.includes('administrador')&&!e.message.includes('constraint'));
assert.equal(db.prepare('SELECT COUNT(*) n FROM pilot_shifts').get().n,1);
for(const e of [Error('UNIQUE constraint failed: pilot_shifts.day'),Error('FOREIGN KEY constraint failed'),Error('no such table: pilot_events'),new TypeError('Cannot read properties of undefined'),new SyntaxError('Unexpected token in JSON')]){const message=userMessage(e);assert(!/constraint|pilot_|undefined|token|table/i.test(message));assert(message.includes('No se pudo'));}
assert(userMessage(Error('database is locked')).includes('ocupado'));const friendly='Ya existe un turno registrado para esta fecha (18/09/2026).';assert.equal(userMessage(Error(friendly)),friendly);assert.equal(userMessage(Error('Completa los campos obligatorios.')),'Completa los campos obligatorios.');
console.log('PASS: duplicate date translated, no duplicate write, database errors and unexpected exceptions never exposed, business explanations preserved.');db.close();
