import assert from 'node:assert/strict';
import {localDatabase} from '../scripts/local-database.mjs';
import {pilotAction,pilotData} from '../dist/pilot/pilot.js';
import {build} from 'rolldown';
const {sqlite:db}=localDatabase(':memory:');
for(const [id,name,role] of [['h','Julieth','Habitual'],['r','Carolina','Reemplazo'],['a','Daniela','Administrador']])db.prepare('INSERT INTO pilot_accounts(id,name,role,salt,pin_hash) VALUES(?,?,?,?,?)').run(id,name,role,'fixture','fixture');
for(const id of ['p','q'])db.prepare('INSERT INTO products(id,code,name,category,minimum,maximum,stock,last_event,created_at) VALUES(?,?,?, ?,0,0,2,?,?)').run(id,id,id,'Montura','original','original');
const original=JSON.stringify(db.prepare('SELECT * FROM products').all());
const data=pilotData(db,null),h=data.accounts.find(a=>a.id==='h'),r=data.accounts.find(a=>a.id==='r'),a=data.accounts.find(a=>a.id==='a');
const deliver={action:'deliver',day:'2026-09-20',observations:'Pendiente estuche.',lines:[{productId:'p',quantity:2},{productId:'q',quantity:2}]};
const shiftId=pilotAction(db,h,deliver).id;pilotAction(db,r,{action:'accept',shiftId});
const lines=db.prepare('SELECT * FROM pilot_lines').all();const counts=lines.map(l=>({lineId:l.id,physical:2,expected:2}));
const close={action:'close',reviewedCounts:true,shiftId,observations:'Falta una montura en el conteo, revisar devolución.',revision:'0:0',counts};
assert.throws(()=>pilotAction(db,r,{...close,reviewedCounts:false}),/físicamente/);assert.throws(()=>pilotAction(db,h,close));assert.throws(()=>pilotAction(db,a,close));assert.throws(()=>pilotAction(db,r,{...close,observations:' '}));assert.throws(()=>pilotAction(db,r,{...close,counts:counts.slice(1)}));assert.throws(()=>pilotAction(db,r,{...close,counts:[counts[0],counts[0]]}));assert.throws(()=>pilotAction(db,r,{...close,counts:[{...counts[0],physical:null},counts[1]]}));assert.throws(()=>pilotAction(db,r,{...close,counts:[{...counts[0],physical:-1},counts[1]]}));assert.throws(()=>pilotAction(db,r,{...close,revision:'old'}));
const event={action:'event',shiftId,lineId:lines[0].id,kind:'Venta',quantity:1,observations:'Venta real.',requestId:'fixture-sale'};pilotAction(db,r,event);
assert.throws(()=>pilotAction(db,r,close),/cambiaron/);
const updated={...close,revision:'1:0',counts:[{...counts[0],expected:1,physical:0},counts[1]]};assert.throws(()=>pilotAction(db,r,updated),/diferencias/);assert.equal(db.prepare('SELECT COUNT(*) n FROM pilot_closures').get().n,0);
pilotAction(db,r,{...updated,acknowledgeDifferences:true,acknowledgedBy:'a'});
const closed=pilotData(db,r);assert.equal(closed.closures[0].acknowledged_by,'r');assert(closed.closures[0].acknowledged_at);assert.equal(closed.closures[0].returned_by,'r');assert.equal(closed.physicalCounts.find(c=>c.line_id===lines[0].id).difference,-1);assert.equal(db.prepare('SELECT balance FROM pilot_lines WHERE id=?').get(lines[0].id).balance,1);
assert(pilotAction(db,r,{...updated,acknowledgeDifferences:true}).duplicate);assert.equal(db.prepare('SELECT COUNT(*) n FROM pilot_closures').get().n,1);
assert.throws(()=>pilotAction(db,r,{...event,requestId:'after-close'}),/bloqueados/);assert.throws(()=>pilotAction(db,r,{action:'annul',shiftId,eventId:closed.events[0].id,observations:'Intento después de devolver.'}),/bloqueados/);
assert.throws(()=>pilotAction(db,h,{...deliver,day:'2026-09-27'}));
const receive={action:'receiveClosure',shiftId,observations:'Recibí el pendiente de diferencia.'};assert.throws(()=>pilotAction(db,r,receive));assert.throws(()=>pilotAction(db,a,receive));assert.throws(()=>pilotAction(db,h,{...receive,observations:''}));pilotAction(db,h,receive);assert(pilotAction(db,h,receive).duplicate);
const final=pilotData(db,h);assert.equal(final.receipts[0].received_by,'h');assert(final.receipts[0].received_at);assert.equal(final.closures[0].returned_by,'r');
const nextId=pilotAction(db,h,{...deliver,day:'2026-09-27'}).id;pilotAction(db,r,{action:'accept',shiftId:nextId});const nextLines=db.prepare('SELECT * FROM pilot_lines WHERE shift_id=?').all(nextId);pilotAction(db,r,{action:'close',reviewedCounts:true,shiftId:nextId,revision:'0:0',observations:'Sin novedades.',counts:nextLines.map(l=>({lineId:l.id,expected:2,physical:2})),acknowledgeDifferences:true});assert.equal(pilotData(db,a).closures.find(c=>c.shift_id===nextId).acknowledged_by,null);
await build({input:'app/pilot-export.ts',platform:'node',output:{dir:'work/closure-export-test',format:'esm',entryFileNames:'export.js'}});const {closureRows}=await import('../work/closure-export-test/export.js');const csv=closureRows('2026-09-20',final.closures[0],final.physicalCounts,lines,final.receipts[0],id=>id);assert.equal(csv[1][10],'r');assert.equal(csv[1][11],final.closures[0].acknowledged_at);assert.equal(csv[1][12],'h');assert.equal(csv[1][4],1);assert.equal(csv[1][5],0);
assert.equal(JSON.stringify(db.prepare('SELECT * FROM products').all()),original);assert.equal(db.prepare('SELECT COUNT(*) n FROM movements').get().n,0);
console.log('PASS: separate physical counts, completeness, stale close protection, audited difference acknowledgment, locked returned shifts, separate receipt, retries, next delivery, CSV evidence and unchanged catalogue.');db.close();
