import assert from 'node:assert/strict';
import {localDatabase} from '../scripts/local-database.mjs';
import {localAccess} from '../scripts/pilot-access.mjs';
import {pilotAction,pilotData} from '../dist/pilot/pilot.js';
const {sqlite:db}=localDatabase(':memory:');
for(const [id,name,role] of [['a','Daniela Figueroa','Administrador'],['h','Julieth Casanova','Inventario'],['r','Carolina Rodriguez','Consulta']])db.prepare('INSERT INTO users(email,name,role,active) VALUES(?,?,?,1)').run(id,name,role);
db.prepare("INSERT INTO products(id,code,name,category,minimum,maximum,stock,last_event,created_at) VALUES('p','FRAME-1','Montura','Montura',0,0,1,'original','original')").run();
db.prepare("INSERT INTO products(id,code,name,category,minimum,maximum,stock,last_event,created_at) VALUES('m','MED-1','Gotas','Medicamento',0,0,2,'original','original')").run();
db.prepare("INSERT INTO lots(id,product_id,number,expiry,stock) VALUES('l','m','L25B15','2027-02-28',2)").run();
const original=JSON.stringify(['products','lots','movements','users'].map(t=>db.prepare('SELECT * FROM '+t).all()));
const access=localAccess(db),pins={'Daniela Figueroa':'135791','Julieth Casanova':'246802','Carolina Rodriguez':'369258'};
assert(pilotData(db,null).setupRequired);access.setup(pins);assert.throws(()=>access.setup(pins));
assert.throws(()=>access.login('r','000000'));const token=access.login('r',pins['Carolina Rodriguez']);const req={headers:{cookie:'pilot_session='+token}};assert.equal(access.me(req).name,'Carolina Rodriguez');access.logout(req);assert.equal(access.me(req),null);
const accounts=pilotData(db,null).accounts,h=accounts.find(a=>a.id==='h'),r=accounts.find(a=>a.id==='r'),a=accounts.find(a=>a.id==='a');
assert.equal(pilotData(db,null).products.length,0);assert(!JSON.stringify(pilotData(db,null)).includes('pin_hash'));
const delivery={action:'deliver',day:'2026-09-20',observations:'Revisar montura y entregar novedades.',lines:[{productId:'p',quantity:1,observations:'Estuche pendiente'},{productId:'m',lotId:'l',quantity:2}]};
assert.throws(()=>pilotAction(db,r,delivery));assert.throws(()=>pilotAction(db,a,delivery));assert.throws(()=>pilotAction(db,h,{...delivery,observations:''}));assert.throws(()=>pilotAction(db,h,{...delivery,day:'2026-09-21'}));
const shiftId=pilotAction(db,h,delivery).id;assert.throws(()=>pilotAction(db,h,delivery));assert.throws(()=>pilotAction(db,h,{action:'accept',shiftId}));pilotAction(db,r,{action:'accept',shiftId});
const line=db.prepare("SELECT id FROM pilot_lines WHERE product_id='p'").get();
const event={action:'event',shiftId,lineId:line.id,kind:'Venta',quantity:1,observations:'Venta con estuche pendiente para relevo.',requestId:'operation-one'};
assert.throws(()=>pilotAction(db,h,event));assert.throws(()=>pilotAction(db,a,event));assert.throws(()=>pilotAction(db,r,{...event,observations:''}));assert.throws(()=>pilotAction(db,r,{...event,quantity:2}));
pilotAction(db,r,event);assert(pilotAction(db,r,event).duplicate);assert.equal(db.prepare('SELECT COUNT(*) n FROM pilot_events').get().n,1);assert.throws(()=>pilotAction(db,r,{...event,quantity:2}));
assert.equal(db.prepare('SELECT balance FROM pilot_lines WHERE id=?').get(line.id).balance,0);
pilotAction(db,r,{...event,kind:'Devolución',requestId:'operation-two',observations:'Cliente devuelve la montura.'});assert.equal(db.prepare('SELECT balance FROM pilot_lines WHERE id=?').get(line.id).balance,1);
assert.equal(db.prepare('SELECT actor FROM pilot_events LIMIT 1').get().actor,'r');
const sale=db.prepare("SELECT * FROM pilot_events WHERE request_id='operation-one'").get();
assert(pilotAction(db,r,{...event,requestId:'double-click-new-id'}).duplicate);
assert.equal(db.prepare('SELECT COUNT(*) n FROM pilot_events').get().n,2);
const cancel={action:'annul',shiftId,eventId:sale.id,observations:'Doble registro de venta.'};
assert.throws(()=>pilotAction(db,a,cancel));assert.throws(()=>pilotAction(db,h,cancel));assert.throws(()=>pilotAction(db,r,{...cancel,observations:''}));
pilotAction(db,r,cancel);assert.equal(db.prepare('SELECT balance FROM pilot_lines WHERE id=?').get(line.id).balance,2);
assert(pilotAction(db,r,cancel).duplicate);assert.equal(db.prepare('SELECT balance FROM pilot_lines WHERE id=?').get(line.id).balance,2);
assert.deepEqual(db.prepare('SELECT * FROM pilot_events WHERE id=?').get(sale.id),sale);
const shown=pilotData(db,r).events.find(e=>e.id===sale.id);assert(shown.annulled_at);assert.equal(shown.annulled_by,'r');assert.equal(shown.annulment_reason,'Doble registro de venta.');
const returned=db.prepare("SELECT id FROM pilot_events WHERE request_id='operation-two'").get();pilotAction(db,r,{...cancel,eventId:returned.id,observations:'Devolución equivocada.'});assert.equal(db.prepare('SELECT balance FROM pilot_lines WHERE id=?').get(line.id).balance,1);
const added=pilotAction(db,r,{...event,kind:'Ajuste positivo',quantity:2,requestId:'positive-adjustment',observations:'Corrección de cantidad.'});
const sold=pilotAction(db,r,{...event,quantity:3,requestId:'sale-after-adjustment',observations:'Venta posterior al ajuste.'});
assert.throws(()=>pilotAction(db,r,{...cancel,eventId:added.id}),/saldo inválido/);assert.equal(db.prepare('SELECT balance FROM pilot_lines WHERE id=?').get(line.id).balance,0);
pilotAction(db,r,{...cancel,eventId:sold.id});pilotAction(db,r,{...cancel,eventId:added.id});assert.equal(db.prepare('SELECT balance FROM pilot_lines WHERE id=?').get(line.id).balance,1);
const subtracted=pilotAction(db,r,{...event,kind:'Ajuste negativo',quantity:1,requestId:'negative-adjustment',observations:'Cantidad mal digitada.'});pilotAction(db,r,{...cancel,eventId:subtracted.id});assert.equal(db.prepare('SELECT balance FROM pilot_lines WHERE id=?').get(line.id).balance,1);
db.prepare("UPDATE pilot_shifts SET status='Entregado' WHERE id=?").run(shiftId);assert.throws(()=>pilotAction(db,r,cancel));
assert.equal(JSON.stringify(['products','lots','movements','users'].map(t=>db.prepare('SELECT * FROM '+t).all())),original);
console.log('PASS: roles, duplicate requests with different IDs, mandatory annulment reasons, reversal of all movement types, repeat-safe annulment, immutable originals, invalid-balance protection and untouched original inventory.');db.close();
