import type {PilotShift,PilotLine,PilotEvent,PhysicalCount,PilotClosure} from './pilot-types';
import {dateLabel} from './types';
export default function PilotSummary({shift,lines,events,counts,closure,actor,showDeliveryNotes=true}:{showDeliveryNotes?:boolean;shift:PilotShift;lines:PilotLine[];events:PilotEvent[];counts:PhysicalCount[];closure?:PilotClosure;actor:(id:string)=>string}){
 const differences=counts.filter(c=>c.difference!==0);
 function countTable(rows:PhysicalCount[]){return <div className="table-wrap"><table><thead><tr><th>Referencia / lote</th><th>Saldo registrado</th><th>Conteo físico</th><th>Diferencia</th></tr></thead><tbody>{rows.map(c=>{const l=lines.find(l=>l.id===c.line_id);return <tr key={c.line_id} className={c.difference?'closure-difference':''}><td>{l?.code} · {l?.name}<small>{l?.lot_number??''}</small></td><td>{c.system_balance}</td><td>{c.physical}</td><td>{c.difference>0?'+':''}{c.difference}</td></tr>})}</tbody></table></div>}
 return <div className="pilot-summary"><h3>Diferencias por referencia ({differences.length})</h3>{differences.length?countTable(differences):<p>{closure?'Sin diferencias entre el conteo físico y el saldo registrado.':'El conteo físico del cierre aún no se ha confirmado.'}</p>}
 <h3>Movimientos registrados ({events.length})</h3>{events.length?<div className="table-wrap"><table><thead><tr><th>Fecha / hora</th><th>Referencia / lote</th><th>Tipo</th><th>Cantidad</th><th>Responsable</th><th>Novedades</th><th>Estado</th></tr></thead><tbody>{events.map(e=>{const l=lines.find(l=>l.id===e.line_id);return <tr key={e.id}><td>{dateLabel(e.created_at)}</td><td>{l?.code}<small>{l?.lot_number??''}</small></td><td>{e.kind}</td><td>{e.quantity}</td><td>{actor(e.actor)}</td><td>{e.observations}{e.annulled_at&&<div><b>Motivo de anulación:</b> {e.annulment_reason}<small>{actor(e.annulled_by!)} · {dateLabel(e.annulled_at)}</small></div>}</td><td>{e.annulled_at?'Anulada':'Vigente'}</td></tr>})}</tbody></table></div>:<p>Sin movimientos registrados.</p>}
 <h3>Novedades / observaciones</h3>{showDeliveryNotes&&<p><b>Entrega:</b> {shift.observations}</p>}{closure&&<p><b>Cierre:</b> {closure.observations}</p>}{showDeliveryNotes&&lines.filter(l=>l.observations.trim()).map(l=><p key={l.id}><b>{l.code}{l.lot_number?' · '+l.lot_number:''}:</b> {l.observations}</p>)}
 <details><summary>Ver inventario completo ({lines.length} referencias / lotes)</summary><div className="table-wrap"><table><thead><tr><th>Referencia / lote</th><th>Entregado</th><th>Saldo registrado</th><th>Observaciones</th></tr></thead><tbody>{lines.map(l=><tr key={l.id}><td>{l.code} · {l.name}<small>{l.lot_number??''}</small></td><td>{l.initial}</td><td>{l.balance}</td><td>{l.observations||'—'}</td></tr>)}</tbody></table></div>{closure&&countTable(counts)}</details></div>;
}
