'use client';
import {useRef,useState} from 'react';
import type {PilotData} from './pilot-types';
import {parseCSV} from './csv';
import {readExcelSheets} from './excel-reader';
import {dateLabel} from './types';
import {CompactWeekReview} from './pilot-week-review';
import {opticalRows,type OpticalRow} from './pilot-optical-import';
type Row=OpticalRow;
type Preview={version:string;references:number;differences:number;cycles:number;pending:{shiftId:string;day:string;status:string;hasClosure:boolean}[];increases:number;decreases:number;missing:string[];rows:{code:string;name:string;lot:string|null;before:number;quantity:number;difference:number;missing?:boolean;rule?:string}[]};
export async function readWeeklyFile(file:File){if(file.size>10000000)throw Error('El archivo debe tener menos de 10 MB.');if(!/\.xlsx$/i.test(file.name))throw Error('Selecciona el Excel real de la óptica (.xlsx), con hojas Monturas y Medicamentos.');return opticalRows(await readExcelSheets(file),file.name);}
export default function WeeklyInventory({data,refresh,onApplied}:{data:PilotData;refresh:()=>Promise<PilotData>;onApplied:()=>void}){
 const input=useRef<HTMLInputElement>(null),lock=useRef(false),viewWeek=useRef('');const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[rows,setRows]=useState<Row[]>([]),[filename,setFilename]=useState(''),[requestId,setRequestId]=useState(''),[originalBase64,setOriginalBase64]=useState(''),[source,setSource]=useState<{filename:string;sheets:{name:string;rows:string[][]}[]} | null>(null),[sourceSheet,setSourceSheet]=useState(0),[sourcePage,setSourcePage]=useState(1),[selectedWeek,setSelectedWeek]=useState('');
 async function post<T=unknown>(body:unknown){const r=await fetch('/api/pilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as T & {error?:string};if(!r.ok)throw Error(d.error??'No se pudo actualizar.');return d;}
 async function read(file:File){if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');setPreview(null);try{const parsed=await readWeeklyFile(file);const p=await post<Preview>({action:'weeklyPreview',format:'optical',rows:parsed});setRows(parsed);setFilename(file.name);const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));setOriginalBase64(btoa(binary));setRequestId(crypto.randomUUID());setPreview(p);}catch(e){setError(e instanceof Error?e.message:'No se pudo leer el archivo.');}finally{lock.current=false;setBusy(false);if(input.current)input.current.value='';}}
 async function apply(acknowledgePending=false){if(lock.current||!preview)return;lock.current=true;setBusy(true);setError('');try{await post({action:'weeklyApply',format:'optical',rows,version:preview.version,filename,requestId,originalBase64,acknowledgePending});setPreview(null);setOriginalBase64('');await refresh();onApplied();setMessage('Inventario base actualizado. Historial conservado; listo para una nueva entrega.');}catch(e){setError(e instanceof Error?e.message:'No se pudo aplicar.');}finally{lock.current=false;setBusy(false);}}
 async function openOriginal(u:PilotData['weeklyUpdates'][number]){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const response=await fetch('/api/pilot/original/'+encodeURIComponent(u.id),{cache:'no-store'});if(!response.ok){const d=await response.json() as {error?:string};throw Error(d.error??'No se pudo abrir el archivo.');}const file=new File([await response.blob()],u.filename);const sheets=/\.csv$/i.test(u.filename)?[{name:'CSV',rows:parseCSV(await file.text())}]:await readExcelSheets(file);if(viewWeek.current!==u.id)return;setSource({filename:u.filename,sheets});setSourceSheet(0);setSourcePage(1);}catch(e){setError(e instanceof Error?e.message:'No se pudo abrir el original.');}finally{lock.current=false;setBusy(false);}}
 return <section className="panel"><h2>Cargar nueva base de datos para nuevo turno</h2><p>Solo Daniela. Selecciona el Excel real de la óptica (.xlsx), con hojas Monturas y Medicamentos. En monturas, cada fila Disponible cuenta como 1 y las demás como 0; los ID ausentes quedan en 0. En medicamentos se usa Stock y se conserva el lote existente. Si falta un medicamento, se conserva su Stock actual y se advierte antes de confirmar.</p><div className="actions"><button className="primary" disabled={busy} onClick={()=>input.current?.click()}>{busy?'Procesando…':'Cargar nueva base de datos para nuevo turno'}</button></div><input hidden ref={input} type="file" accept=".xlsx" onChange={e=>{const f=e.target.files?.[0];if(f)void read(f);}}/>{error&&<div className="notice error" role="alert">{error}</div>}{message&&<div className="notice success" role="status">{message}</div>}
 {preview&&<div className="notice"><h3>Revisar antes de confirmar</h3><p>{filename}: <b>{preview.references} referencias</b> ({preview.rows.length} referencias / lotes), <b>{preview.differences} con diferencias</b> frente al inventario base actual. Se archivarán {preview.cycles} turnos con todos los registros que tienen actualmente.</p><p><b>Suben:</b> {preview.increases} · <b>Bajan:</b> {preview.decreases} · <b>No aparecieron:</b> {preview.missing.length}</p>{preview.missing.length>0&&<div className="notice closure-warning" role="alert"><b>Posibles faltantes:</b> {preview.missing.join(', ')}<p>Revisa estas referencias. Las monturas ausentes quedarán en 0; los medicamentos ausentes conservarán su Stock actual.</p></div>}{preview.pending.length>0&&<div className="notice closure-warning" role="alert"><h3>Hay turnos sin recepción confirmada</h3>{preview.pending.map(p=><p key={p.shiftId}>El turno del {p.day.split('-').reverse().join('/')} aún no ha sido confirmado por el equipo habitual.{!p.hasClosure?' Tampoco se ha registrado su cierre.':''} Si continúas, quedará archivado tal como está, incluyendo la falta de esa confirmación.</p>)}<p>Continuar no cierra, acepta ni confirma el turno. Tu decisión de archivar estos pendientes quedará registrada con tu nombre y fecha/hora.</p><button className="secondary" disabled={busy} onClick={()=>setPreview(null)}>Esperar, sin aplicar cambios</button></div>}<p>Al confirmar se conserva el historial completo y el sistema queda sin turno activo. No se modifican nombres, referencias, datos de lote ni usuarios/PINs.</p><div className="table-wrap"><table><thead><tr><th>Referencia / lote</th><th>Base actual</th><th>Nueva cantidad física</th><th>Diferencia</th><th>Origen / faltante</th></tr></thead><tbody>{preview.rows.map((r,i)=><tr key={i} className={r.difference?'closure-difference':''}><td>{r.code} · {r.name}<small>{r.lot??''}</small></td><td>{r.before}</td><td>{r.quantity}</td><td>{r.difference>0?'+':''}{r.difference}</td><td>{r.rule}</td></tr>)}</tbody></table></div><div className="actions"><button className="secondary" disabled={busy} onClick={()=>setPreview(null)}>Cancelar</button><button className="primary" disabled={busy} onClick={()=>void apply(preview.pending.length>0)}>{preview.pending.length?'Continuar de todas formas y archivar':'Confirmar actualización y archivar ciclo'}</button></div></div>}
 <section className="weekly-history"><h2>Historial de cargas de inventario</h2>{!data.weeklyUpdates.length&&<p>Aún no hay cargas de inventario confirmadas.</p>}<ul className="weekly-date-list">{data.weeklyUpdates.map(u=><li key={u.id}><a href={'#semana-'+u.id} aria-current={selectedWeek===u.id?'true':undefined} onClick={e=>{e.preventDefault();viewWeek.current=selectedWeek===u.id?'':u.id;setSelectedWeek(viewWeek.current);setSource(null);}}>{new Date(u.created_at).toLocaleDateString('es-CO',{timeZone:'America/Bogota',day:'2-digit',month:'long',year:'numeric'})}</a></li>)}</ul>
 {data.weeklyUpdates.filter(u=>u.id===selectedWeek).map(u=><article id={'semana-'+u.id} key={u.id}><details onToggle={e=>{if(e.currentTarget.open&&u.hasOriginal&&!source)void openOriginal(u);}}><summary>Ver base de datos cargada</summary><p>Solo lectura. Selecciona la hoja para consultar sus celdas.</p>{!u.hasOriginal&&<p>El archivo original de esta carga no está disponible.</p>}{busy&&<p>Leyendo archivo…</p>}{source&&<><label>Hoja<select value={sourceSheet} onChange={e=>{setSourceSheet(Number(e.target.value));setSourcePage(1);}}>{source.sheets.map((s,i)=><option key={i} value={i}>{s.name}</option>)}</select></label><div className="table-wrap"><table><tbody>{source.sheets[sourceSheet]?.rows.slice((sourcePage-1)*50,sourcePage*50).map((r,i)=><tr key={i}><th>Fila {(sourcePage-1)*50+i+1}</th>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div><div className="actions"><button className="secondary" disabled={sourcePage===1} onClick={()=>setSourcePage(p=>p-1)}>Anterior</button><span>Página {sourcePage} de {Math.max(1,Math.ceil((source.sheets[sourceSheet]?.rows.length??0)/50))}</span><button className="secondary" disabled={sourcePage*50>=(source.sheets[sourceSheet]?.rows.length??0)} onClick={()=>setSourcePage(p=>p+1)}>Siguiente</button></div></>}</details><details><summary>Resumen integrador</summary><CompactWeekReview data={data} updateId={u.id}/></details></article>)}</section></section>;
}
