import type {PilotData,PilotShift} from './pilot-types';
import {dateLabel} from './types';
import PilotSummary from './pilot-summary';
export function shiftsForWeek(data:PilotData,updateId:string){
 const ordered=[...data.weeklyUpdates].sort((a,b)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id));
 const index=ordered.findIndex(u=>u.id===updateId);if(index<0)return [];
 const start=ordered[index].created_at,end=ordered[index+1]?.created_at;
 return data.shifts.filter(s=>s.delivered_at>=start&&(!end||s.delivered_at<end)).sort((a,b)=>a.day.localeCompare(b.day));
}
export default function WeekReview({data,updateId}:{data:PilotData;updateId:string}){
 const shifts=shiftsForWeek(data,updateId),actor=(id:string)=>data.accounts.find(a=>a.id===id)?.name??id;
 const lines=(s:PilotShift)=>data.lines.filter(l=>l.shift_id===s.id),events=(s:PilotShift)=>data.events.filter(e=>e.shift_id===s.id),counts=(s:PilotShift)=>data.physicalCounts.filter(c=>c.shift_id===s.id),closure=(s:PilotShift)=>data.closures.find(c=>c.shift_id===s.id);
 return <div className="weekly-review"><p>Esta semana comprende los turnos entregados después de esta carga y antes de la siguiente. Los ciclos anteriores archivados al cargar pertenecen a la base que estaba vigente antes.</p>{!shifts.length&&<div className="notice">Aún no hay turnos entregados con esta base semanal.</div>}
 <details><summary>Movimientos de Julieth</summary>{shifts.map(s=><article key={s.id}><h3>Entrega · {s.day.split('-').reverse().join('/')}</h3><p>Entregó: {actor(s.delivered_by)} · {dateLabel(s.delivered_at)}</p><p><b>Novedades de entrega:</b> {s.observations}</p><div className="table-wrap"><table><thead><tr><th>Referencia / lote</th><th>Cantidad entregada</th><th>Novedades</th></tr></thead><tbody>{lines(s).map(l=><tr key={l.id}><td>{l.code} · {l.name}<small>{l.lot_number??''}</small></td><td>{l.initial}</td><td>{l.observations||'—'}</td></tr>)}</tbody></table></div></article>)}</details>
 <details><summary>Movimientos de Carolina</summary>{shifts.map(s=><article key={s.id}><h3>Operación y cierre · {s.day.split('-').reverse().join('/')}</h3><p>{s.accepted_at?'Recibió: '+actor(s.accepted_by!)+' · '+dateLabel(s.accepted_at):'Recepción inicial pendiente.'}</p><PilotSummary shift={s} lines={lines(s)} events={events(s)} counts={counts(s)} closure={closure(s)} actor={actor} showDeliveryNotes={false}/>{closure(s)&&<p>Devolvió: {actor(closure(s)!.returned_by)} · {dateLabel(closure(s)!.returned_at)}</p>}<details><summary>Ver conteo físico completo</summary><div className="table-wrap"><table><thead><tr><th>Referencia / lote</th><th>Saldo registrado</th><th>Conteo físico</th><th>Diferencia</th></tr></thead><tbody>{counts(s).map(c=>{const l=lines(s).find(l=>l.id===c.line_id);return <tr key={c.line_id}><td>{l?.code} · {l?.lot_number??'—'}</td><td>{c.system_balance}</td><td>{c.physical}</td><td>{c.difference}</td></tr>})}</tbody></table></div></details></article>)}</details>
 <h3>Resumen integrador del fin de semana</h3>{shifts.map(s=>{const c=closure(s),r=data.receipts.find(r=>r.shift_id===s.id);return <article key={s.id}><h4>{s.day.split('-').reverse().join('/')} · {r?'Cierre recibido':c?'Devuelto · recepción pendiente':data.archivedShiftIds?.includes(s.id)?'Archivado sin cierre confirmado':s.status}</h4><PilotSummary shift={s} lines={lines(s)} events={events(s)} counts={counts(s)} closure={c} actor={actor}/><p>Confirmó entrega: {actor(s.delivered_by)} · {dateLabel(s.delivered_at)}</p>{s.accepted_at&&<p>Confirmó recepción inicial: {actor(s.accepted_by!)} · {dateLabel(s.accepted_at)}</p>}{c?<><p>Confirmó devolución: {actor(c.returned_by)} · {dateLabel(c.returned_at)}</p>{c.acknowledged_at&&<div className="notice closure-warning">Reconoció la alerta de diferencias y decidió continuar: {actor(c.acknowledged_by!)} · {dateLabel(c.acknowledged_at)}</div>}</>:<p>Devolución del cierre pendiente.</p>}{r?<><p>Confirmó recepción del cierre: {actor(r.received_by)} · {dateLabel(r.received_at)}</p><p><b>Novedades al recibir:</b> {r.observations}</p></>:<p>Recepción del cierre pendiente.</p>}</article>})}</div>;
}
export function CompactWeekReview({data,updateId}:{data:PilotData;updateId:string}){
 const shifts=shiftsForWeek(data,updateId),u=data.weeklyUpdates.find(u=>u.id===updateId),missing=u?JSON.parse(u.quantities_json).rows.filter((r:any)=>r.missing):[];
 return <div>{missing.length>0&&<><h3>Referencias ausentes en la base cargada</h3><ul>{missing.map((r:any)=><li key={r.code}>{r.code} · {r.name}</li>)}</ul></>}{!shifts.length&&<p>Aún no hay movimientos registrados para esta semana.</p>}{shifts.map(s=>{const lines=data.lines.filter(l=>l.shift_id===s.id),shortages=data.physicalCounts.filter(c=>c.shift_id===s.id&&c.difference<0),events=data.events.filter(e=>e.shift_id===s.id),c=data.closures.find(c=>c.shift_id===s.id),r=data.receipts.find(r=>r.shift_id===s.id);return <article key={s.id}><h3>{s.day.split('-').reverse().join('/')}</h3><h4>Faltantes del conteo físico</h4>{shortages.length?<ul>{shortages.map(c=><li key={c.line_id}>{lines.find(l=>l.id===c.line_id)?.code} · Faltan {Math.abs(c.difference)} unidades</li>)}</ul>:<p>{c?'Sin faltantes en el conteo físico.':'Conteo físico aún no registrado.'}</p>}<h4>Movimientos de Julieth</h4><p><b>Entrega inicial:</b> {s.observations}</p>{lines.filter(l=>l.observations.trim()).map(l=><p key={l.id}>{l.code}: {l.observations}</p>)}{r&&<p><b>Novedades al recibir:</b> {r.observations}</p>}<h4>Movimientos de Carolina</h4>{events.length?<div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Referencia</th><th>Movimiento</th><th>Cantidad</th><th>Novedades</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{dateLabel(e.created_at)}</td><td>{lines.find(l=>l.id===e.line_id)?.code}</td><td>{e.kind}{e.annulled_at?' · Anulada':''}</td><td>{e.quantity}</td><td>{e.observations}{e.annulled_at&&<p>Motivo de anulación: {e.annulment_reason}</p>}</td></tr>)}</tbody></table></div>:<p>Sin operaciones registradas.</p>}{c&&<p><b>Novedades del cierre:</b> {c.observations}</p>}</article>})}</div>;
}
