'use client';
import {useState,type FormEvent} from 'react';
import {X} from 'lucide-react';
import {categories,today,type Product,type Lot,type Account,type Order} from './types';
export type Dialog={type:'product'|'movement'|'thresholds'|'user'|'receive';product?:Product;user?:Account;order?:Order;defaultCategory?:string};
export default function ProductDialog({dialog,lots,busy,error,onClose,onSave}:{dialog:Dialog;lots:Lot[];busy:boolean;error:string;onClose:()=>void;onSave:(payload:Record<string,unknown>)=>void}){
 const [category,setCategory]=useState(dialog.defaultCategory??'Montura'),[direction,setDirection]=useState('Entrada'),[newLot,setNewLot]=useState(false);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=Object.fromEntries(new FormData(e.currentTarget));const payload:Record<string,unknown>={...form,action:dialog.type,productId:dialog.product?.id};if(dialog.type==='product'){payload.unitPrice=form.unitPrice===''?null:Number(form.unitPrice);payload.stock=Number(form.stock);payload.minimum=Number(form.minimum);payload.maximum=Number(form.maximum)}if(dialog.type==='thresholds'){payload.minimum=Number(form.minimum);payload.maximum=Number(form.maximum)}if(dialog.type==='user')payload.active=Number(form.active);if(dialog.type==='movement'||dialog.type==='receive'){payload.quantity=Number(form.quantity);payload.orderId=dialog.order?.id;payload.kind=dialog.type==='receive'?'Entrada':direction;}onSave(payload)}
 const productLots=lots.filter(l=>l.product_id===dialog.product?.id);
 return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title" onKeyDown={e=>{if(e.key==='Escape'&&!busy)onClose()}}><div className="dialog-head"><h2 id="dialog-title">{{product:'Registrar producto',movement:'Registrar movimiento',thresholds:'Configurar reposición',user:dialog.user?'Editar usuario':'Agregar usuario',receive:'Recibir compra'}[dialog.type]}</h2><button aria-label="Cerrar" disabled={busy} onClick={onClose}><X size={20}/></button></div>{dialog.product&&<p className="notice">{dialog.product.code} · {dialog.product.name} · {dialog.product.stock} unidades</p>}{error&&<div className="notice error" role="alert">{error}</div>}<form onSubmit={submit}><div className="form-grid">
 {dialog.type==='product'&&<><label>Código único<input name="code" required maxLength={80} autoFocus placeholder="Ej.: M-0001"/></label><label>Categoría<select name="category" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="full">Nombre del producto<input name="name" required maxLength={200}/></label>{[['brand','Marca'],['model','Modelo / referencia'],['color','Color'],['size','Talla / calibre'],['location','Ubicación'],['supplier','Proveedor']].map(([n,l])=><label key={n}>{l}<input name={n} maxLength={200}/></label>)}{category==='Montura'&&<><label>Tipo de montura<select name="frameCategory"><option value="">Sin especificar</option><option>Solar</option><option>Oftálmica</option></select></label><label>Fecha ingreso<input name="entryDate" type="date"/></label></>}<label>Precio por unidad (COP)<input name="unitPrice" type="number" min="0" max="1000000" step="1"/></label><label>Unidad de conteo<select name="unit"><option>Unidad</option><option>Caja</option><option>Par</option></select></label><label>Existencias iniciales<input name="stock" type="number" required min="0" max="1000000" step="1" defaultValue="0"/></label><label>Mínimo<input name="minimum" type="number" required min="0" max="1000000" step="1" defaultValue="0"/></label><label>Máximo<input name="maximum" type="number" required min="0" max="1000000" step="1" defaultValue="0"/></label>{category==='Medicamento'&&<><p className="help full">Si registras unidades iniciales, indica su lote y vencimiento. Cada nueva entrada puede añadir otro lote.</p><label>Lote<input name="lot" maxLength={80}/></label><label>Vencimiento<input name="expiry" type="date" min={today()}/></label></>}</>}
 {dialog.type==='thresholds'&&<><label>Mínimo<input name="minimum" type="number" min="0" max="1000000" step="1" required defaultValue={dialog.product?.minimum}/></label><label>Máximo<input name="maximum" type="number" min="0" max="1000000" step="1" required defaultValue={dialog.product?.maximum}/></label><label>Proveedor<input name="supplier" maxLength={200} defaultValue={dialog.product?.supplier}/></label><label>Ubicación<input name="location" maxLength={200} defaultValue={dialog.product?.location}/></label><p className="help full">La solicitud pendiente se actualiza con estos límites. Las compras ya aprobadas mantienen su cantidad.</p></>}
 {['movement','receive'].includes(dialog.type)&&<>{dialog.type==='movement'?<label>Tipo<select name="kind" value={direction} onChange={e=>{setDirection(e.target.value);setNewLot(false)}}><option>Entrada</option><option>Salida</option></select></label>:<p className="notice full">Compra aprobada · Pendientes de recibir: {(dialog.order?.quantity??0)-(dialog.order?.received??0)} unidades.</p>}<label>Cantidad<input name="quantity" type="number" min="1" max={dialog.type==='receive'?(dialog.order!.quantity-dialog.order!.received):1000000} step="1" required autoFocus/></label>{direction==='Salida'&&<label>Motivo de salida<select name="reason"><option>Venta o uso</option><option>Daño</option><option>Vencimiento</option><option>Devolución</option></select></label>}{dialog.product?.category==='Medicamento'&&<>{direction==='Entrada'&&productLots.length>0&&<label className="check full"><input type="checkbox" checked={newLot} onChange={e=>setNewLot(e.target.checked)}/>Registrar un lote nuevo</label>}{!newLot&&productLots.length>0?<label className="full">Lote<select name="lotId" required defaultValue=""><option value="" disabled>Selecciona un lote</option>{productLots.map(l=><option key={l.id} value={l.id}>{l.number} · Vence {l.expiry} · {l.stock} unidades</option>)}</select></label>:direction==='Entrada'?<><label>Número de lote<input name="lot" required maxLength={80}/></label><label>Vencimiento<input name="expiry" type="date" min={today()} required/></label></>:<p className="notice error full">Este medicamento no tiene lotes para registrar una salida.</p>}</>}<label className="full">Detalle del movimiento<textarea name="note" required maxLength={500} rows={3} placeholder="Referencia de compra, venta o explicación de la salida"/></label></>}
 {dialog.type==='user'&&<><label>Nombre<input name="name" required maxLength={200} defaultValue={dialog.user?.name} autoFocus/></label><input type="hidden" name="userKey" value={dialog.user?.email??''}/><label>Perfil<select name="role" defaultValue={dialog.user?.role??'Inventario'}><option value="Administrador">Administrador</option><option value="Inventario">Encargada de inventario</option><option value="Consulta">Consulta</option></select></label><label>Estado<select name="active" defaultValue={dialog.user?.active??1}><option value={1}>Activo</option><option value={0}>Inactivo</option></select></label></>}
 </div><div className="form-footer"><button type="button" className="secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary" disabled={busy} type="submit">{busy?'Guardando…':'Guardar'}</button></div></form></section></div>
}
