'use client';
import {useState,type ReactNode} from 'react';
import {Download,Printer} from 'lucide-react';
import {today,dateLabel,type Snapshot} from './types';
import {csvDownload} from './csv';
export default function Reports({data,from,to,dates}:{data:Snapshot;from:string;to:string;dates:ReactNode}){
const [report,setReport]=useState('Existencias'),[page,setPage]=useState(1);const products=data.products;
function rows():unknown[][]{if(report==='Movimientos')return [['Fecha','Código','Producto','Lote','Tipo','Cambio','Antes','Después','Motivo','Usuario'],...data.movements.map(m=>[dateLabel(m.created_at),m.code,m.name,m.lot_number??'',m.kind,m.delta,m.before,m.after,m.note,m.actor])];if(report==='Conteos')return [['Fecha','Código','Producto','Lote','Frecuencia','Periodo','Registrado','Contado','Diferencia','Usuario'],...data.counts.map(c=>[dateLabel(c.created_at),c.code,c.name,c.lot_number??'',c.frequency,c.period,c.expected,c.actual,c.actual-c.expected,c.actor])];if(report==='Reposición')return [['Fecha','Código','Producto','Proveedor','Solicitado','Recibido','Estado','Aprobado por'],...data.orders.map(o=>[dateLabel(o.created_at),o.code,o.name,o.supplier,o.quantity,o.received,o.status,o.approved_by])];if(report==='Lotes')return [['Código','Producto','Lote','Vencimiento','Existencias','Estado'],...data.lots.map(l=>{const p=products.find(p=>p.id===l.product_id);return [p?.code,p?.name,l.number,l.expiry,l.stock,l.expiry<today()?'Vencido':'Vigente']})];return [['Código','Producto','Categoría','Marca','Modelo','Color','Talla','Ubicación','Existencias','Mínimo','Máximo','Proveedor','Unidad','Precio unitario COP'],...products.map(p=>[p.code,p.name,p.category,p.brand,p.model,p.color,p.size,p.location,p.stock,p.minimum,p.maximum,p.supplier,p.unit,p.unit_price])]}
const reportRows=rows(),total=reportRows.length-1;
return <div className="panel"><div className="panel-title"><h2>Informe de {report.toLowerCase()}</h2><div className="actions"><button className="secondary" disabled={data.truncated&&['Movimientos','Conteos'].includes(report)} onClick={()=>csvDownload('informe-'+report.toLowerCase()+'-'+today(),reportRows)}><Download size={16}/>Descargar CSV</button><button className="secondary" onClick={()=>window.print()}><Printer size={16}/>Imprimir / PDF</button></div></div><div className="toolbar"><select aria-label="Tipo de informe" value={report} onChange={e=>{setReport(e.target.value);setPage(1)}} style={{width:'auto'}}>{['Existencias','Movimientos','Conteos','Reposición','Lotes'].map(s=><option key={s}>{s}</option>)}</select></div>{['Movimientos','Conteos'].includes(report)?dates:<p className="muted">Estado actual al {dateLabel(new Date().toISOString())}. Este informe no es un saldo histórico.</p>}<p className="print-heading">OPTICALIA OptiStock IA · Informe de {report.toLowerCase()} · {['Movimientos','Conteos'].includes(report)?from+' a '+to:today()}</p><div className="table-wrap"><table><thead><tr>{reportRows[0].map((h,i)=><th key={i}>{String(h)}</th>)}</tr></thead><tbody>{reportRows.slice(1).slice((page-1)*25,page*25).map((row,i)=><tr key={i}>{row.map((c,j)=><td key={j}>{String(c??'—')}</td>)}</tr>)}</tbody></table>{!total&&<div className="empty">No hay registros para este informe.</div>}</div><div className="pagination"><span>{total} registros · Página {page} de {Math.max(1,Math.ceil(total/25))}</span><button className="secondary" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</button><button className="secondary" disabled={page*25>=total} onClick={()=>setPage(p=>p+1)}>Siguiente</button></div><p className="help">El CSV incluye todos los registros del informe. La impresión muestra la página actual.</p></div>
}
