import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,blob,uniqueIndex,index,check} from 'drizzle-orm/sqlite-core';
export const pilotClosures=sqliteTable('pilot_closures',{shiftId:text('shift_id').primaryKey().references(()=>pilotShifts.id),observations:text('observations').notNull(),returnedBy:text('returned_by').notNull().references(()=>pilotAccounts.id),returnedAt:text('returned_at').notNull(),acknowledgedBy:text('acknowledged_by').references(()=>pilotAccounts.id),acknowledgedAt:text('acknowledged_at')});
export const pilotPhysicalCounts=sqliteTable('pilot_physical_counts',{lineId:text('line_id').primaryKey().references(()=>pilotLines.id),shiftId:text('shift_id').notNull().references(()=>pilotClosures.shiftId),systemBalance:integer('system_balance').notNull(),physical:integer('physical').notNull(),difference:integer('difference').notNull()},t=>[check('physical_nonnegative',sql`${t.physical}>=0`)]);
export const pilotReceipts=sqliteTable('pilot_receipts',{shiftId:text('shift_id').primaryKey().references(()=>pilotClosures.shiftId),receivedBy:text('received_by').notNull().references(()=>pilotAccounts.id),receivedAt:text('received_at').notNull(),observations:text('observations').notNull()});
export const pilotAnnulments=sqliteTable('pilot_annulments',{eventId:text('event_id').primaryKey().references(()=>pilotEvents.id),observations:text('observations').notNull(),actor:text('actor').notNull().references(()=>pilotAccounts.id),createdAt:text('created_at').notNull(),beforeBalance:integer('before_balance').notNull(),afterBalance:integer('after_balance').notNull()},t=>[check('annulment_balance',sql`${t.afterBalance}>=0`)]);
export const pilotAccounts=sqliteTable('pilot_accounts',{id:text('id').primaryKey(),name:text('name').notNull(),role:text('role').notNull(),salt:text('salt').notNull(),pinHash:text('pin_hash').notNull()},t=>[check('pilot_role',sql`${t.role} IN ('Habitual','Reemplazo','Administrador')`)]);
export const pilotShifts=sqliteTable('pilot_shifts',{id:text('id').primaryKey(),day:text('day').notNull(),retired:integer('retired').notNull().default(0),holiday:integer('holiday').notNull().default(0),observations:text('observations').notNull(),status:text('status').notNull(),deliveredBy:text('delivered_by').notNull().references(()=>pilotAccounts.id),deliveredAt:text('delivered_at').notNull(),acceptedBy:text('accepted_by').references(()=>pilotAccounts.id),acceptedAt:text('accepted_at')},t=>[uniqueIndex('pilot_shifts_current_day').on(t.day).where(sql`${t.retired}=0`),check('pilot_status',sql`${t.status} IN ('Entregado','En curso')`)]);
export const pilotLines=sqliteTable('pilot_lines',{id:text('id').primaryKey(),shiftId:text('shift_id').notNull().references(()=>pilotShifts.id),productId:text('product_id').notNull().references(()=>products.id),lotId:text('lot_id').references(()=>lots.id),code:text('code').notNull(),name:text('name').notNull(),lotNumber:text('lot_number'),expiry:text('expiry'),initial:integer('initial').notNull(),balance:integer('balance').notNull(),observations:text('observations').notNull()},t=>[uniqueIndex('pilot_line_reference').on(t.shiftId,t.productId,t.lotId),check('pilot_initial',sql`${t.initial}>=0`),check('pilot_balance',sql`${t.balance}>=0`)]);
export const pilotEvents=sqliteTable('pilot_events',{id:text('id').primaryKey(),requestId:text('request_id').notNull().unique(),shiftId:text('shift_id').notNull().references(()=>pilotShifts.id),lineId:text('line_id').notNull().references(()=>pilotLines.id),kind:text('kind').notNull(),quantity:integer('quantity').notNull(),beforeBalance:integer('before_balance').notNull(),afterBalance:integer('after_balance').notNull(),observations:text('observations').notNull(),actor:text('actor').notNull().references(()=>pilotAccounts.id),createdAt:text('created_at').notNull()},t=>[check('pilot_kind',sql`${t.kind} IN ('Venta','Devolución','Ajuste positivo','Ajuste negativo')`),check('pilot_quantity',sql`${t.quantity}>0`),check('pilot_after',sql`${t.afterBalance}>=0`)]);
export const products=sqliteTable('products',{id:text('id').primaryKey(),code:text('code').notNull().unique(),name:text('name').notNull(),category:text('category').notNull(),brand:text('brand').notNull().default(''),model:text('model').notNull().default(''),color:text('color').notNull().default(''),size:text('size').notNull().default(''),location:text('location').notNull().default(''),frameCategory:text('frame_category'),entryDate:text('entry_date'),supplier:text('supplier').notNull().default(''),unitPrice:integer('unit_price'),unit:text('unit').notNull().default('Unidad'),minimum:integer('minimum').notNull(),maximum:integer('maximum').notNull(),stock:integer('stock').notNull().default(0),lastEvent:text('last_event').notNull(),createdAt:text('created_at').notNull()},t=>[check('stock_nonnegative',sql`${t.stock} >= 0`),check('thresholds_valid',sql`${t.minimum} >= 0 AND ${t.maximum} >= ${t.minimum}`)]);
export const lots=sqliteTable('lots',{id:text('id').primaryKey(),productId:text('product_id').notNull().references(()=>products.id),number:text('number').notNull(),expiry:text('expiry').notNull(),stock:integer('stock').notNull().default(0)},t=>[uniqueIndex('lots_product_number').on(t.productId,t.number),check('lot_stock_nonnegative',sql`${t.stock} >= 0`)]);
export const users=sqliteTable('users',{email:text('email').primaryKey(),name:text('name').notNull(),role:text('role').notNull(),active:integer('active').notNull().default(1)});
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const movements=sqliteTable('movements',{id:text('id').primaryKey(),productId:text('product_id').notNull().references(()=>products.id),lotId:text('lot_id').references(()=>lots.id),kind:text('kind').notNull(),delta:integer('delta').notNull(),before:integer('before').notNull(),after:integer('after').notNull(),note:text('note').notNull(),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[index('movements_date').on(t.createdAt)]);
export const counts=sqliteTable('counts',{id:text('id').primaryKey(),productId:text('product_id').notNull().references(()=>products.id),lotId:text('lot_id').references(()=>lots.id),frequency:text('frequency').notNull(),period:text('period').notNull(),expected:integer('expected').notNull(),actual:integer('actual').notNull(),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[index('counts_period').on(t.frequency,t.period)]);
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),productId:text('product_id').notNull().references(()=>products.id),quantity:integer('quantity').notNull(),received:integer('received').notNull().default(0),status:text('status').notNull().default('Pendiente'),approvedBy:text('approved_by'),createdAt:text('created_at').notNull()},t=>[uniqueIndex('orders_open_product').on(t.productId).where(sql`${t.status} IN ('Pendiente','Aprobada')`),check('order_valid_quantities',sql`${t.quantity}>0 AND ${t.received}>=0 AND ${t.received}<=${t.quantity}`)]);
export const pilotWeeklyUpdates=sqliteTable('pilot_weekly_updates',{id:text('id').primaryKey(),actor:text('actor').notNull().references(()=>pilotAccounts.id),createdAt:text('created_at').notNull(),filename:text('filename').notNull(),snapshotJson:text('snapshot_json').notNull(),quantitiesJson:text('quantities_json').notNull()});
export const pilotArchivedShifts=sqliteTable('pilot_archived_shifts',{shiftId:text('shift_id').primaryKey().references(()=>pilotShifts.id),updateId:text('update_id').notNull().references(()=>pilotWeeklyUpdates.id)});

export const pilotWeeklyOriginals=sqliteTable('pilot_weekly_originals',{updateId:text('update_id').primaryKey().references(()=>pilotWeeklyUpdates.id),bytes:blob('bytes',{mode:'buffer'}).notNull(),mime:text('mime').notNull(),sha256:text('sha256').notNull()});

export const pilotResets=sqliteTable('pilot_resets',{id:text('id').primaryKey(),shiftId:text('shift_id').notNull().references(()=>pilotShifts.id),actor:text('actor').notNull().references(()=>pilotAccounts.id),createdAt:text('created_at').notNull(),reason:text('reason').notNull(),snapshotJson:text('snapshot_json').notNull()});
